[package]
name = "rust-render"
version = "0.1.0"
authors = ["Alexey Skrobotov <Alexey.Skrobotov@softeq.com>"]
edition = "2018"

[[bin]]
name = "rust_render"
path = "src/main.rs"

[dependencies]
image = "0.21.1"