[package]
name = "rust-render"
version = "0.1.0"
authors = ["Alexey Skrobotov <Alexey.Skrobotov@softeq.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"
scan_fmt = "0.1.3"
sdl2 = "0.32.2"
log = "0.3"